version: "4"
services:

  appium-hub:
    image: android-emulator
    build: .
    privileged: true
    ports:
      - 44723:44723
    environment:
      - APPIUM_PORT=44723
    command:
      - bash
      - -c
      - |
         ./start_appium.sh hub
    tty: true
    stdin_open: true


# Launch emulator and appium instance
  android-service:
    image: seimage/android-sdk
    build: .
    container_name: android
    privileged: true
    ports:
      - 44724:44724
    environment:
      - APPIUM_PORT=44724
    command:
      - bash
      - -c
      - |
         ./start_emu_headless.sh
    tty: true
    stdin_open: true
